apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
      - name: redis-config-volume
        configMap:
          name: redis-config
      containers:
      - image: redis:6.2.3-alpine
        name: redis
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
        volumeMounts:
        - name: redis-config-volume
          mountPath: /usr/local/etc/redis

        livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5