apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-commander
  name: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - image: rediscommander/redis-commander:latest
        name: redis
        env:
        - name: REDIS_HOSTS
          value: "redis_server:redis:6379"